forge 'https://forgeapi.puppetlabs.com'

mod "puppetlabs/apt",
   :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "puppetlabs/stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "puppetlabs/ntp",
   :git => "git://github.com/puppetlabs/puppetlabs-ntp.git"

mod "batanga-uy/timezone",
  :git => "git@bitbucket.org:batanga-uy/puppet-timezone.git"

